version: 0.2
        
phases:
  install:
    commands:
      - npm install 
  build:
    commands:
      - npm run build
      - npm run cdk synth
artifacts:
  files:
    - cdk.out/*
    - lambda-test/*
  name: pattern3.zip
  discard-paths: no
  base-directory: $CODEBUILD_SRC_DIR

